services:
  - type: web
    name: duolingo-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    preDeployCommand: "python manage.py migrate && python manage.py seed_data && python manage.py ensure_superuser"
    startCommand: "gunicorn duolingo_backend.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        value: 891167565350-6bgbmm3gbqrrba6fdk54lfm4g6ts6f8b.apps.googleusercontent.com
